apiVersion: charts.nginx.org/v1beta1
kind: NginxIngress
metadata:
  name: nginx-ingress-controller
  namespace: default
spec:
  controller:
    defaultTLS:
      secret: nginx-ingress/default-server-secret
    image:
      pullPolicy: IfNotPresent
      repository: nginx/nginx-ingress
      tag: 2.3.1-ubi
    ingressClass: nginx
    kind: deployment
    nginxplus: false
    replicaCount: 1
    serviceAccount:
      imagePullSecretName: ""