apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecast-core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forecast-core
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: forecast-core
    spec:
      containers:
        - name: forecast-core
          image: registry.gitlab.com/admirai/diploma_forecast/forecast-core:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: weather-forecast-config
            - secretRef:
                 name: weather-forecast-secret
      imagePullSecrets:
        - name: regcred
