apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forecast
spec:
  ingressClassName: ingress-class
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forecast-client
                port:
                  number: 80