apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecast-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: forecast-client
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: forecast-client
    spec:
      containers:
        - image: registry.gitlab.com/admirai/diploma_forecast/forecast-client:latest
          name: forecast-client
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: weather-forecast-config
            - secretRef:
                name: weather-forecast-secret
      imagePullSecrets:
        - name: regcred
