apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecast-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: forecast-client
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: forecast-client
    spec:
      containers:
        - image: registry.gitlab.com/admirai/forecast/forecast-client:latest
          name: forecast-client
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: weather-forecast-config
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8092
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8092
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 10
      imagePullSecrets:
        - name: regcred
