version: '3.3'

services:

  core:
    build:
      context: ../forecast
      dockerfile: Dockerfile

  client:
    build:
      context: ../forecastClient
      dockerfile: Dockerfile

    depends_on:
      - core