version: '3.3'

services:

  core:
    build:
      context: ../forecastCore
      dockerfile: Dockerfile
    container_name: forecast-core
    ports:
      - "8081:8081"


  client:
    build:
      context: ../forecastClient
      dockerfile: Dockerfile
    container_name: forecast-client
    ports:
      - "8082:8082"
    depends_on:
      - core

  bot:
    build:
      context: ../forecastBot
      dockerfile: Dockerfile
    container_name: forecast-bot
    ports:
      - "8085:8085"
    depends_on:
      - client